<a href="https://colab.research.google.com/github/Kaushal-Top5699/tensorflow_01/blob/main/tensorflow_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# importing tensorlfow
import tensorflow as tf

In [4]:
# Creating tensors with tf.Variable()
tf.Variable

tensorflow.python.ops.variables.Variable

In [5]:
# Creating same tensor as previous with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchanegable_tensor = tf.constant([10, 7])
changeable_tensor, unchanegable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [6]:
# Let's try changing one of the elements of our changeable_tensor
changeable_tensor[0].assign(7)
changeable_tensor[1].assign(10)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [10]:
unchanegable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [14]:
from tensorflow._api.v2 import random
# Creating two random tensors
random_1 = tf.random.Generator.from_seed(7) 
random_1 = random_1.normal(shape = (3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape = (3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
# Shuffling of tensor data
not_shuffled = tf.constant([[1, 2], 
                            [4, 5],
                            [7, 8]])
not_shuffled.ndim

2

In [21]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [25]:
# Shuffling our not_shuffled tensor
# Shuffles along the 1st dimension
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5],
       [1, 2]], dtype=int32)>