<a href="https://colab.research.google.com/github/Kaushal-Top5699/tensorflow_01/blob/main/tensorflow_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# importing tensorlfow
import tensorflow as tf

In [4]:
# Creating tensors with tf.Variable()
tf.Variable

tensorflow.python.ops.variables.Variable

In [5]:
# Creating same tensor as previous with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchanegable_tensor = tf.constant([10, 7])
changeable_tensor, unchanegable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [6]:
# Let's try changing one of the elements of our changeable_tensor
changeable_tensor[0].assign(7)
changeable_tensor[1].assign(10)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [10]:
unchanegable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [14]:
from tensorflow._api.v2 import random
# Creating two random tensors
random_1 = tf.random.Generator.from_seed(7) 
random_1 = random_1.normal(shape = (3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape = (3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
# Shuffling of tensor data
not_shuffled = tf.constant([[1, 2], 
                            [4, 5],
                            [7, 8]])
not_shuffled.ndim

2

In [21]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [25]:
# Shuffling our not_shuffled tensor
# Shuffles along the 1st dimension
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5],
       [1, 2]], dtype=int32)>

In [7]:
my_tensor = tf.constant([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])
my_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [10]:
tf.random.shuffle(my_tensor, seed = 42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]], dtype=int32)>

In [12]:
# Creating tensor of all ones and zeros, just like numpy
ones_tensor = tf.ones([4, 4])
ones_tensor

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [14]:
zeros_tensor =tf.zeros([4, 4])
zeros_tensor 

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [16]:
# Turning numpy arrays into tensor
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [19]:
A = tf.constant(numpy_A, shape=(3, 8))
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [21]:
A.ndim

2

In [23]:
# Shape, Rank, Axis or Dimension, and Size
# Creating a rank 4 tensor (4 Dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
print(tf.size(rank_4_tensor)) 
print(rank_4_tensor.dtype)
print(tf.shape(rank_4_tensor))
print(rank_4_tensor.shape[-1])

tf.Tensor(120, shape=(), dtype=int32)
<dtype: 'float32'>
tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
5
